# ------------------------------------------------
# 1. Build GoSearch
# ------------------------------------------------
FROM golang:1.25-bookworm AS builder

RUN go install github.com/ibnaleem/gosearch@latest

FROM tsl0922/ttyd:1.7.8 as ttyd

# ------------------------------------------------
# 2. Runtime avec terminal Web
# ------------------------------------------------
FROM debian:bookworm-slim

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        bash \
        curl \
        vim \
        nano \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# On récupère le binaire compilé
COPY --from=builder /go/bin/gosearch /usr/local/bin/gosearch

COPY --from=ttyd /usr/bin/ttyd /usr/local/bin/ttyd

# Port HTTP utilisé par ttyd
EXPOSE 7681

RUN useradd -ms /bin/bash factory-frequency-user

WORKDIR /workspace

RUN chown -R factory-frequency-user:factory-frequency-user /workspace

USER factory-frequency-user

# -W = terminal modifiable
# bash = ouvre un vrai terminal dans le navigateur
CMD ["ttyd", "-W", "-p", "7681", "bash"]
