FROM dmachard/dnscollector:latest AS dnscollector

FROM tsl0922/ttyd:1.7.8 as ttyd

FROM debian:bookworm-slim

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        bash \
        curl \
        vim \
        nano \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# On récupère le binaire compilé
COPY --from=dnscollector /bin/dnscollector /usr/local/bin/dnscollector

# On récupère le package TTYD 
COPY --from=ttyd /usr/bin/ttyd /usr/local/bin/ttyd

# Port HTTP utilisé par ttyd
EXPOSE 7681

RUN useradd -ms /bin/bash factory-frequency-user

WORKDIR /workspace

RUN chown -R factory-frequency-user:factory-frequency-user /workspace && chmod -R 755 /workspace

USER factory-frequency-user

CMD ["ttyd", "-W", "-p", "7681", "bash"]
